### ISSUE TITLE
如果after-state training 把 alpha 設定 > 0.1, 會發生 exception

### ISSUE THREAD

**Issue by huanggeorg** [2018-summer-DL-training-program/Lab-4-2048#3]
Dear TA,

如果把 alpha 設定為其他比 0.1 大的值, 似乎很容易發生 numeric exception

此時看 debug info 會看到 exact/update 會出現很不合理的極大或極小的數

分析之後, 發現可能是因為強迫假設 V(S(t-1), after-state) == V(S(t), before-state)  造成

以下圖為例, 在 forward phase, S’ 可能被賦予很高的 value, 

但是是因為之前某次 nice play, 從 S’ ==>B’’ ==> B’’’ 導致

但是 B’’ 不必然是 S’ 的未來, 假設這次的未來是 S’’, 結果最後得到一個很低的分數

那麼這次 backward phase 從 S’’ ==>S’, 用 S’’ 的 exact = 50 去強迫 S’ 要從 100000 往 50 去更新, 就顯得不合理了

這個更新的意圖會造成巨大 error 往 value function table 的32個 entries 擴散.

另外對於像是 [0] 這種很常出現在board 上的 pattern 來說, 它可能很常被更新, 

但有很大多數的更新是由於 isometrics 造成, 而非因為它實際出現在 board 上. 

這樣很可能也對導致這種entry的值很不穩定.

請問這個現象是已知的限制嗎?? 或是說已經存在有解法???

謝謝!!!

![image](https://user-images.githubusercontent.com/41607716/45663782-cd337900-bb3a-11e8-9a27-2bce9b458fe2.png)

**Comment by lukewayne123** [comment]
我自己測試也是 alpha > 0.1程式會有問題 (也是數值太大或太小[應該是 overflow])
跟出題學長討論後，目前的結論是

2048的分數是以2的等比級數的總和會累加起來，即使已經是用2的指數來記錄，對於起始盤面所累加的分數還是很可觀，加上使用 n-tuple network與其 isomorphic 盤面來記錄一個盤面的分數(請參考我9/19上傳的 slides)，所以如果 alpha設定太大，不論用 float, double等，累加到一定程度後，都會 overflow

另外，alpha可以想做 CNN中的 learning rate，其實 learning rate不能設太大，會導致無法到達 optimal solution，而 0.1是對於 2048這個 project算較大 learning rate，如果要讓 model更好，實際上是要把 alpha調小

**Comment by huanggeorg** [comment]
Hi Luke,

我後來有找到一個可能的原因與解法.

https://github.com/2018-summer-DL-training-program/Lab-4-2048/issues/4

請您參考看看.

Thank you
